---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task
    tag: latest

params:
  CONTEXT: code-repo-modified

inputs:
  - name: code-repo-modified
    path: .

outputs:
  - name: image

caches:
  - path: cache

run:
  path: build