---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudpipelines/pipeline-base
    tag: latest

inputs:
- name: code-repo
- name: ci-repo

run:
  path: ci-repo/ci/tasks/build.sh