---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudpipelines/pipeline-base
    tag: latest

inputs:
- name: code-repo
- name: ci-repo
- name: maven-repo

outputs:
  - name: code-repo
  - name: maven-repo

run:
  path: ci-repo/ci/tasks/init-env.sh
  args:
    - ci-repo/ci/tasks/test-producer.sh

