---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudpipelines/pipeline-base
    tag: latest

inputs:
  - name: code-repo
  - name: ci-repo
  - name: stubs-repo

outputs:
  - name: code-repo-modified
  - name: stubs-repo-modified

run:
  path: ci-repo/ci/tasks/init-env.sh
  args:
    - ci-repo/ci/tasks/test.sh
