---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudpipelines/pipeline-base
    tag: latest

inputs:
  - name: code-repo
  - name: devops-repo
  - name: ci-repo

outputs:
  - name: devops-repo

run:
  path: ci-repo/ci/tasks/update-k8s-devops-yamls.sh