project-name: s1p-hello-client
code-repo-uri: https://github.com/msathe-tech/s1p-hello-client.git
code-repo-branch: master
gitops-repo-uri: git@github.com:msathe-tech/s1p-hello-client-devops-k8s.git
gitops-repo-branch: master
