---
resource_types:
  - name: file-url
    type: docker-image
    source:
      repository: pivotalservices/concourse-curl-resource
      tag: latest

resources:
- name: code-repo
  type: git
  source:
    uri: ((code-repo-uri))
    branch: ((code-repo-branch))

- name: maven-repo
  type: git
  source:
    uri: ((maven-repo-uri))
    branch: ((maven-repo-branch))
    private_key: ((github-private-key))

- name: devops-repo
  type: git
  source:
    uri: ((devops-repo-uri))
    branch: ((devops-repo-branch))
    private_key: ((github-private-key))

- name: ci-repo
  type: git
  source:
    uri: ((ci-repo-uri))
    branch: ((ci-repo-branch))

- name: ci-cloud-pipelines
  type: file-url
  source:
    url: ((ci-cloud-pipelines-file))
    filename: ((ci-cloud-pipelines-file-name))

- name: app-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/((project-name))

jobs:
- name: test-build-publish
  public: true
  serial: true
  plan:
  - get: code-repo
    trigger: true
  - get: ci-repo
  - get: ci-cloud-pipelines
  - get: maven-repo
  - task: build
    file: ci-repo/ci/tasks/test-build-publish.yml
  - put: app-docker-image
    params:
      build: code-repo

#- name: update-k8s-devops-yamls
##  public: false
#  serial: true
#  plan:
#    # get sha from code repo and update image tag yml in devops repo
#    - get: code-repo
#    - get: devops-repo
#    - get: ci-repo
#      passed:
#      - build-and-publish
#      trigger: true
#    - task: update-k8s-devops-yamls
#      file: ci-repo/ci/tasks/update-k8s-devops-yamls.yml
#    - put: devops-repo
#      params: {repository: devops-repo-modified}