---
resource_types:
resources:
- name: code-repo
  type: git
  source:
    uri: ((code-repo-uri))
    branch: ((code-repo-branch))

- name: stubs-repo
  type: git
  source:
    uri: ((stubs-repo-uri))
    branch: ((stubs-repo-branch))
    private_key: ((github-private-key))

- name: gitops-repo
  type: git
  source:
    uri: ((gitops-repo-uri))
    branch: ((gitops-repo-branch))
    private_key: ((github-private-key))

- name: ci-repo
  type: git
  source:
    uri: ((ci-repo-uri))
    branch: ((ci-repo-branch))

- name: app-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/((project-name))

jobs:
- name: test
  public: true
  serial: true
  plan:
  - get: code-repo
    trigger: true
  - get: ci-repo
  - get: stubs-repo
  - task: test
    file: ci-repo/ci/tasks/test.yml
  - put: stubs-repo
    params: {repository: stubs-repo}
  - put: app-docker-image
    params:
      build: code-repo
      tag_file: code-repo/DockerTagfile
      additional_tags: code-repo/DockerAdditionalTagsfile

- name: update-gitops
#  public: false
  serial: true
  plan:
    # Update image tag in deployment yamls
    - get: code-repo
    - get: gitops-repo
    - get: ci-repo
      passed:
      - test
      trigger: true
    - task: update-gitops
      file: ci-repo/ci/tasks/update-gitops.yml
    - put: gitops-repo
      params: {repository: gitops-repo-modified}