---
#resource_types:
#- name: registry-image
#  type: docker-image
#  source:
#    repository: concourse/registry-image-resource
#    tag: latest

resources:
- name: code-repo
  type: git
  source:
    uri: ((code-repo-uri))
    branch: ((code-repo-branch))

- name: stubs-repo
  type: git
  source:
    uri: ((stubs-repo-uri))
    branch: ((stubs-repo-branch))
    private_key: ((github-private-key))

- name: gitops-repo
  type: git
  source:
    uri: ((gitops-repo-uri))
    branch: ((gitops-repo-branch))
    private_key: ((github-private-key))

- name: ci-repo
  type: git
  source:
    uri: ((ci-repo-uri))
    branch: ((ci-repo-branch))

#- name: image-registry
#  type: docker-image
#  source:
#    email: ((docker-hub-email))
#    username: ((docker-hub-username))
#    password: ((docker-hub-password))
#    repository: ((docker-hub-username))/((project-name))

- name: image-registry
  type: registry-image
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/((project-name))

jobs:
- name: test-build-publish
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: code-repo
      trigger: true
    - get: ci-repo
    - get: stubs-repo
  - task: test
    file: ci-repo/ci/tasks/test.yml
  - task: build-image
    file: ci-repo/ci/tasks/build-image.yml
  - put: stubs-repo
    params: {repository: stubs-repo-modified}
  - put: image-registry
    params:
      image: image/image.tar
      additional_tags: code-repo-modified/Dockertags
#  - put: image-registry
#    params:
#      build: code-repo
#      tag_file: code-repo/DockerTagfile
#      additional_tags: code-repo/DockerAdditionalTagsfile


- name: update-gitops
#  public: false
  serial: true
  plan:
    # Update image tag in deployment yamls
    - get: code-repo
    - get: gitops-repo
    - get: ci-repo
      passed:
      - test-build-publish
      trigger: true
    - task: update-gitops
      file: ci-repo/ci/tasks/update-gitops.yml
    - put: gitops-repo
      params: {repository: gitops-repo-modified}