---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  #name: nginx-ingress-serviceaccount
  name: nginx-ingress-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: nginx-ingress-serviceaccount
    #namespace: ingress-nginx
    namespace: hello
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
